In [37]:
#imprtant libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
import os

In [38]:
#directories
orginal_dir='/home/usama/Desktop/obd2_project'
data_dir='/home/usama/Desktop/obd2_project/OBD II Dataset'

In [39]:
#import csv directory folder
dataset=os.path.join(data_dir,"Modified_OBDII.csv")

In [45]:
#read csv file
dataframe=pd.read_csv(dataset)

In [46]:
#set the values
data_set=dataframe.values

In [76]:
#apply get dummies to convert string data into binary form
dataset=pd.get_dummies(dataframe,prefix_sep='_',drop_first=False)
dataset.head()

,Longitude,Latitude,GPS Speed (Meters/second),Horizontal Dilution of Precision,Altitude,Bearing,G(x),G(y),G(z),G(calibrated),...,Mass Air Flow Rate(g/s),Throttle Position(Manifold)(%),Date,Year,Hours,Minutes,Seconds,Day_Thu,Month_Nov,Time zone_CDT
0,-97.662474,30.483089,2.795157,93,250,211.6,0.350434,9.163701,-2.947818,0.000910,...,33.759998,32.549019,2,2017,15,44,24,1,1,1
1,-97.662476,30.483068,0.000000,98,255,0.0,-6.745979,4.394452,-4.039574,-0.062790,...,37.200001,32.549019,2,2017,15,44,25,1,1,1
2,-97.662478,30.483006,0.000000,105,247,0.0,-0.923281,7.736757,3.870868,-0.094130,...,35.180000,37.647060,2,2017,15,44,26,1,1,1
3,-97.662546,30.482689,0.000000,101,225,0.0,-4.792311,2.172633,16.387754,0.773513,...,38.040001,39.215687,2,2017,15,44,27,1,1,1
4,-97.662546,30.482689,0.000000,101,225,0.0,-0.061368,7.190879,6.686449,0.038575,...,39.349998,38.823528,2,2017,15,44,27,1,1,1

In [77]:
k=5
k_means=KMeans(n_clusters=k,init='k-means++',n_init=12)
k_means.fit(dataset)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=5, n_init=12, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [80]:
label=k_means.labels_

In [81]:
dataset['Outcomes']=label

In [85]:
dataset.to_csv(r'/home/usama/Desktop/obd2_project/OBD II Dataset/complete_labeled_OBDII.csv',index=False)